site_name: HSI classifier v1.0 Documentation
nav:
    - Home: index.md
    - Getting Started: howtobegin.md
    - Class Definitions: labelInfo.md
    - Band Selection: bandselection.md
    - Spectral Classification Methods: classificationmethods.md
    - RGB Segmentation Methods: rgbSegmentation.md
    - Spectral-Spatial Classification Methods: spectralspatialclassify.md
    - HSI to RGB Conversion: hsitorgb.md
    - Helper Functions: helperfun.md

theme: 
    name: material
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
        - matlab
        - python